ALTER TABLE "delivery_orders"
  ADD COLUMN IF NOT EXISTS "customer_id" integer,
  ADD COLUMN IF NOT EXISTS "offered_amount" numeric(10, 2),
  ADD COLUMN IF NOT EXISTS "required_vehicle_type" varchar(100),
  ADD COLUMN IF NOT EXISTS "vehicle_base_price" numeric(10, 2),
  ADD COLUMN IF NOT EXISTS "price_per_km" numeric(10, 2),
  ADD COLUMN IF NOT EXISTS "distance_km" numeric(10, 2),
  ADD COLUMN IF NOT EXISTS "final_delivery_price" numeric(10, 2),
  ADD COLUMN IF NOT EXISTS "pricing_frozen_at" timestamp,
  ADD COLUMN IF NOT EXISTS "temporary_winner_id" integer,
  ADD COLUMN IF NOT EXISTS "approved_at" timestamp,
  ADD COLUMN IF NOT EXISTS "preferred_vehicle" varchar(100),
  ADD COLUMN IF NOT EXISTS "quota" integer DEFAULT 10 NOT NULL,
  ADD COLUMN IF NOT EXISTS "current_orders_count" integer DEFAULT 0 NOT NULL,
  ADD COLUMN IF NOT EXISTS "pickup_lat" numeric(10, 7),
  ADD COLUMN IF NOT EXISTS "pickup_lng" numeric(10, 7),
  ADD COLUMN IF NOT EXISTS "dropoff_lat" numeric(10, 7),
  ADD COLUMN IF NOT EXISTS "dropoff_lng" numeric(10, 7),
  ADD COLUMN IF NOT EXISTS "route_distance" varchar(50),
  ADD COLUMN IF NOT EXISTS "route_duration" varchar(50),
  ADD COLUMN IF NOT EXISTS "route_polyline" text;
